### ISSUE TITLE
Maybe enrich the analysis of dependencies through an alternate provider?

### ISSUE THREAD

**Issue by nulltoken** [axa-ch/metalsmith-postcss#18]
PR #16 brings scanning of deps through nodesecurity.io, by comapring the package versions against their advisories (https://nodesecurity.io/advisories/).

It may be worthwhile to also plug Snyk in, in order to enhance the coverage (https://snyk.io/vuln/?type=npm).

Thoughts?

**Comment by sventschui** [comment]
NSP & Snyk are integrated
