### ISSUE TITLE
Test fixtures aren't cross platform compliant

### ISSUE THREAD

**Issue by nulltoken** [axa-ch/metalsmith-postcss#19]
Running `npm test` on a Windows box issues the following:

```bash

> metalsmith-postcss@4.1.0 test C:\tmp\metalsmith-postcss
> mocha test --harmony



  metalsmith-postcss
    sourcemaps

      √ should not add sourcemaps at all

      1) should add inline sourcemaps

      2) should add external sourcemap files

      √ should pass absolute paths to postcss (39ms)

      √ should be able to use arrays as a way to define plugins


  3 passing (118ms)
  2 failing

  1) metalsmith-postcss sourcemaps should add inline sourcemaps:

      Uncaught AssertionError: 'body {\r\n  color: peachpuff;\r\n}\r\n\r\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInN == 'body {\r\n  color: peachpuff;\r\n}\r\n\r\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInN
      + expected - actual

       body {
         color: peachpuff;
       }
       
      -/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInN0eWxlcy5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7RUFDRSxpQkFBaUI7Q0FDbEIiLCJmaWxlIjoic3R5bGVzLmNzcyIsInNvdXJjZXNDb250ZW50IjpbImJvZHkge1xyXG4gIGNvbG9yOiBwZWFjaHB1ZmY7XHJcbn1cclxuIl19 */
      +/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInN0eWxlcy5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7RUFDRSxpQkFBaUI7Q0FDbEIiLCJmaWxlIjoic3R5bGVzLmNzcyIsInNvdXJjZXNDb250ZW50IjpbImJvZHkge1xuICBjb2xvcjogcGVhY2hwdWZmO1xufVxuIl19 */
      
      at C:\tmp\metalsmith-postcss\node_modules\assert-dir-equal\lib\index.js:35:14
      at Array.forEach (native)
      at assertDirEqual (C:\tmp\metalsmith-postcss\node_modules\assert-dir-equal\lib\index.js:31:11)
      at equalIndependentlyOfNewlines (C:\tmp\metalsmith-postcss\test\index.js:16:7)
      at Metalsmith.<anonymous> (C:\tmp\metalsmith-postcss\test\index.js:41:11)
      at Immediate.<anonymous> (C:\tmp\metalsmith-postcss\node_modules\unyield\node_modules\co\index.js:52:14)

  2) metalsmith-postcss sourcemaps should add external sourcemap files:

      Uncaught AssertionError: '{"version":3,"sources":["styles.css"],"names":[],"mappings":"AAAA;EACE,iBAAiB;CAClB","file":"styles.css","sourcesContent":["bod == '{"version":3,"sources":["styles.css"],"names":[],"mappings":"AAAA;EACE,iBAAiB;CAClB","file":"styles.css","sourcesContent":["bod
      + expected - actual

      -{"version":3,"sources":["styles.css"],"names":[],"mappings":"AAAA;EACE,iBAAiB;CAClB","file":"styles.css","sourcesContent":["body {\r\n  color: peachpuff;\r\n}\r\n"]}
      +{"version":3,"sources":["styles.css"],"names":[],"mappings":"AAAA;EACE,iBAAiB;CAClB","file":"styles.css","sourcesContent":["body {\n  color: peachpuff;\n}\n"]}
      
      at C:\tmp\metalsmith-postcss\node_modules\assert-dir-equal\lib\index.js:35:14
      at Array.forEach (native)
      at assertDirEqual (C:\tmp\metalsmith-postcss\node_modules\assert-dir-equal\lib\index.js:31:11)
      at equalIndependentlyOfNewlines (C:\tmp\metalsmith-postcss\test\index.js:16:7)
      at Metalsmith.<anonymous> (C:\tmp\metalsmith-postcss\test\index.js:57:11)
      at Immediate.<anonymous> (C:\tmp\metalsmith-postcss\node_modules\unyield\node_modules\co\index.js:52:14)
```

Problem seems to lie in `test\fixtures\`xxxxx-sourcemaps\expected\*` files where the Unlix-like `LF` line ending separator is hardcoded  (either within the base64 encoded content (inline) or within a string (external)).

**Comment by sventschui** [comment]
Is this fixed by your PR that I merged recently?

**Comment by nulltoken** [comment]
>Is this fixed by your PR that I merged recently?

Nope.

I'm ok to work on a fix, but I'm not sure about what behavior is expected.

When being run on Windows, should every line ending to normalized to `LF` or `CRLF`?

**Comment by sventschui** [comment]
We would need to transform `require('os').EOL` into `\n` before comparing it to the fixtures. That's my guess. Other opinions?

**Comment by sventschui** [comment]
Think we should PR to https://github.com/ianstormtaylor/assert-dir-equal to allow for an option to convert newlines

**Comment by nulltoken** [comment]
>We would need to transform require('os').EOL into \n before comparing it to the fixtures. That's my guess. Other opinions?

That would make indeed the tests always pass.

But what would be the impact of running the plug-in production on a Windows environment? Unless I'm wrong, that would generate sourcemaps containing `CRLF` for all end users.

My understanding is that sourcemaps are used to allow live-in browser view of the original style. So the line ending of the server should actually be irrelevant.

However, do all browsers, on Windows, accept and honor `LF` as a line ending in sourcemaps (either inline or external)?

Sorry for the newbie question here. I'm not really proficient into css debugging user experience.

**Comment by nulltoken** [comment]
> Think we should PR to https://github.com/ianstormtaylor/assert-dir-equal to allow for an option to convert newlines

That may be an option and would actually solve our issue with failing tests. However, are we sure client-side *nix browsers properly deal with `CRLF`s in sourcemaps?

**Comment by sventschui** [comment]
Good point. I think a CRLF is not an issue since the superfluous CR doesn't harm anything. But have not tested this so far. LF should be handled by all major browsers since I never experienced any issues and we build on linux and I'm running a Chrome on Windows at work.

Since PostCSS is generating the sourcemaps it is more a PostCSS related issue generating CRLF stuff on windows. If you want that fixed you would best fix that in PostCSS.

We can altough fix or tests to work on windows too.

**Comment by sventschui** [comment]
Seems that UglifyJS always produces LF, so LF shouldn't be an issue at all. And CRLF is no issue since superfluous CR's are ignore by nix systems
