### ISSUE TITLE
Autoprefixer

### ISSUE THREAD

**Issue by karneaud** [axa-ch/metalsmith-postcss#4]
Does it make use of autoprefixing? Or do I need to handle it with metalsmith-autoprefixer?

**Comment by davidknezic** [comment]
The `metalsmith-postcss` plugin accepts an array with `postcss` plugins. That's the place where you can add `autoprefixer`. It doesn't execute any plugins by default.

``` js
var postcss = require('metalsmith-postcss');

metalsmith.use(postcss(plugins));
```

Here's an example of how you could use `autoprefixer`:

``` js
var Metalsmith = require('metalsmith');
var postcss = require('metalsmith-postcss');
var autoprefixer = require('autoprefixer');

Metalsmith(__dirname)
  .use(postcss([
    autoprefixer({ browsers: ['last 2 versions'] })
    // add more postcss plugins here
  ]))
  .build(function (err) {
    if (err) throw err;
  });
```

**Comment by karneaud** [comment]
@davidknezic Thanks for the feedback I thought so but wondered why someone went ahead with the plugin for metalsmith.
