### ISSUE TITLE
Metalsmith · error using plugin "metalsmith-postcss"...

### ISSUE THREAD

**Issue by karneaud** [axa-ch/metalsmith-postcss#5]
I'm trying to use your posts pplugin with the autoprefixer plugin my .json file is

```
"metalsmith-postcss": {
        "input": "build/css/*.css",
        "output": "*.css",
        "autoprefixer": {
            "browsers": ["> 5%"]
        }
    },
```

but when running I get the following task error

> undefined is not a function
> 
> TypeError: undefined is not a function
>    at main (/path/to/node_modules/metalsmith-
>   postcss/index.js:11:11)
>   at path/to/node_modules/metalsmith/bin/_metalsmith:93:22
>   at Array.forEach (native)
>    at Object.<anonymous> 
>   (/path/to/node_modules/metalsmith/bin/_metalsmith:72:25)
>   at Module._compile (module.js:460:26)
>    at Object.Module._extensions..js (module.js:478:10)
>   at Module.load (module.js:355:32)
>    at Function.Module._load (module.js:310:12)
>    at Function.Module.runMain (module.js:501:10)
>   at startup (node.js:129:16)

Do  I have the configuration right?

**Comment by davidknezic** [comment]
Unfortunately, this plugin doesn't support being used from the `metalsmith.json` file. The only way to get it to work is with the [JavaScript API](https://github.com/axa-ch/metalsmith-postcss#javascript-api).

If you only want to prefix your css files and don't want to switch to a JavaScript build, just use the less generic [`metalsmith-autoprefix`](https://github.com/esundahl/metalsmith-autoprefixer):

It allows you to do the following:

``` json
{
  "plugins": {
    "metalsmith-autoprefixer": {
      "browsers": ["> 5%"]
    }
  }
}
```

It automatically targets all your `*.css` files, so no need for `input` and `output` properties.

**Comment by karneaud** [comment]
crap!
