### ISSUE TITLE
Plugins array?

### ISSUE THREAD

**Issue by donovanh** [axa-ch/metalsmith-postcss#7]
I think I'm being daft but I can't work out what format the array of plugins needs to be. Can we get an example?

Edit: Yes, I'm daft. I had to require each plugin as usual then create an array of each like:

var postcss_import = require('postcss-import'),
    postcss_nested = require('postcss-nested');

var plugins = [postcss_import, postcss_nested];

I'm sure it could be optimised better but this got things going.

**Comment by davidknezic** [comment]
Even though you made it work, I extended the README file with a simple example on how to add plugins. Hopefully we can help future users of this plugin to get started easier.

Thanks for your feedback @donovanh!
